### ISSUE TITLE
Techstack: interface

### ISSUE THREAD

**Issue by Plouc314** [GenoRobotics-EPFL/Database#3]
## Input / Output
* Quelle partie du projet interagit avec la base de données ?
* Tech ?
  * Interface graphique (ex: webapp)
  * standalone [REST API](https://realpython.com/api-integration-in-python/)
  * command line interface (CLI)
  * librairie python

**Comment by seorimpark** [comment]
![InterfaceDiagram](https://user-images.githubusercontent.com/56107891/196244350-3fdfe49e-21c5-404b-a063-2140958bfa35.png)

**Comment by seorimpark** [comment]
On avait un webapp avant, on peut toujours changer

**Comment by Plouc314** [comment]
Dans ce cas il faut une API sur le NAS (si c'est possible ?) et choisir une tech pour la webapp (on field): est-ce qu'on part sur du full frontend (react, vue, ...) sans backend ou sur quelque chose du type .jsp (jinja est l'équivalent avec flask je crois) où il faudrait sûrement une API (on field)

**Comment by Plouc314** [comment]
**Techstack**
- [Next.js](https://nextjs.org/docs) (framework based on [React](https://reactjs.org/))
- [Mantine UI](https://mantine.dev/) (UI components library)
- [typescript](https://www.typescriptlang.org/) (superset of javascript)

@melinacherchali pour commencer: regarde les bases de:
- javascript
- html / css
- react

Pour l'instant, les éléments suivants ne sont pas importants:
- [Next.js](https://nextjs.org/docs)
- [Mantine UI](https://mantine.dev/)
- [typescript](https://www.typescriptlang.org/)

**Comment by melinacherchali** [comment]
D'accord je regarde ça!
