### ISSUE TITLE
Techstack: web framework

### ISSUE THREAD

**Issue by Plouc314** [GenoRobotics-EPFL/Database#4]
Choix de la framework à utiliser:
* [Flask](https://flask.palletsprojects.com/en/2.2.x/) (léger)
* [Django](https://www.djangoproject.com/) (lourd)
* [FastAPI](https://fastapi.tiangolo.com/) (nouveau...)
 
Comparaison: 
* [flask vs django](https://www.kicklox.com/blog-client/flask-vs-django-framework-python/)
* [flask vs FastAPI](https://www.netguru.com/blog/python-flask-versus-fastapi)

**Comment by lipefree** [comment]
D'après la discussion sur le discord, on va partir sur FastAPI.
