### ISSUE TITLE
Design du structure de la base de données

### ISSUE THREAD

**Issue by seorimpark** [GenoRobotics-EPFL/Database#6]

**Comment by seorimpark** [comment]
![DatabaseDiagram](https://user-images.githubusercontent.com/56107891/196244276-ee2841d2-cc23-4f74-b293-e3ea0b898532.png)

**Comment by Plouc314** [comment]
Quelqu'un peut déjà commencer la structure de la db. 
En utilisant [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy) ou les scirpts MySQL existant (je sais pas ce que c'est) ou autre...
Implémenter les opérations de bases:
* Créer les tableaux
* Insérer des éléments
* Lire des éléments
* Supprimer des éléments

**Comment by Plouc314** [comment]
@seorimpark  Je poste comment j'ai compris la structure de la db à partir des input forms de l'interface et du schéma en dessus. Dit moi si tu vois des erreurs / si il manque quelque chose.

![db_schemas](https://user-images.githubusercontent.com/51334065/201467588-0cd4a689-8ca7-4cbc-8dd7-cdd88ae9e66b.png)

**Comment by Plouc314** [comment]
marker = barcode (10-15 base pairs)
